# 仓库配置
repository:
  url: "${REPO_URL:-git@github.com:projecy-icey/icey-storage.git}"
  clone_path: "${CLONE_PATH:-/app/data}"
  ssh_key: "${SSH_KEY_PATH:-/app/my_ed25519_key}"
  username: ""
  password: ""

# Redis 配置
redis:
  ip: "${REDIS_IP:-redis}"
  port: ${REDIS_PORT:-6379}
  password: "${REDIS_PASSWORD:-}"

# 验证码配置
verification:
  max_attempts: 15

# 微信公众号配置
wechat:
  app_id: "${WECHAT_APP_ID:-}"
  app_secret: "${WECHAT_APP_SECRET:-}"
  token: "${WECHAT_TOKEN:-}"
  encoding_aes_key: "${WECHAT_ENCODING_AES_KEY:-}"

# 服务器配置
server:
  port: ${SERVER_PORT:-37080}
  host: "${SERVER_HOST:-0.0.0.0}"

# 日志配置
logging:
  level: "${LOG_LEVEL:-info}"
  format: "${LOG_FORMAT:-json}"