version: '3.8'

services:
  # 主应用服务
  app:
    image: meeaicey/meea-icey
    container_name: meea-icey-app
    restart: unless-stopped
    ports:
      - "37080:37080"
    volumes:
      - app_data:/app/data
      - ./config.yaml:/app/config.yaml:ro
      - ./my_ed25519_key:/app/my_ed25519_key:ro
      - ./my_ed25519_key.pub:/app/my_ed25519_key.pub:ro
    environment:
      - TZ=Asia/Shanghai
    networks:
      - meea-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:37080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  app_data:
    driver: local

networks:
  meea-network:
    driver: bridge 