version: '3.8'

services:
  # Redis 服务
  redis:
    image: redis:7-alpine
    container_name: meea-icey-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - meea-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 主应用服务
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meea-icey-app
    restart: unless-stopped
    ports:
      - "37080:37080"
    volumes:
      - app_data:/app/data
      - ./config.yaml:/app/config.yaml:ro
      - ./my_ed25519_key:/app/my_ed25519_key:ro
      - ./my_ed25519_key.pub:/app/my_ed25519_key.pub:ro
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - meea-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:37080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  redis_data:
    driver: local
  app_data:
    driver: local

networks:
  meea-network:
    driver: bridge 